# Generated by Django 5.2 on 2025-05-15 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0005_tag_color_alter_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(default='#808080', max_length=7),
        ),
    ]
