# Generated by Django 5.2 on 2025-05-20 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0008_holiday'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Holiday',
        ),
    ]
